# Generated by Django 5.1.2 on 2024-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIDailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('morning_tip', models.TextField()),
                ('mid_morning_tip', models.TextField()),
                ('afternoon_tip', models.TextField()),
                ('evening_tip', models.TextField()),
                ('exercise_tip', models.TextField()),
                ('relaxation_tip', models.TextField()),
                ('work_tip', models.TextField()),
            ],
        ),
    ]
