# Generated by Django 5.1.2 on 2024-11-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBasedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(choices=[('Morning', '6 AM - 10 AM'), ('Midday', '10 AM - 2 PM'), ('Afternoon', '2 PM - 6 PM'), ('Evening', '6 PM - 10 PM'), ('Night', '10 PM - 6 AM')], max_length=20)),
                ('suggestion_text', models.TextField(help_text='Suggestion for this time period')),
                ('applicable_for', models.CharField(choices=[('General', 'General'), ('Diabetes', 'Diabetes')], default='General', help_text='Choose the target audience', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='productivitysuggestion',
            name='bmi_category',
        ),
        migrations.DeleteModel(
            name='DietPlan',
        ),
        migrations.DeleteModel(
            name='ProductivitySuggestion',
        ),
    ]
