# Generated by Django 5.1.2 on 2024-11-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0005_bmicategory_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebasedsuggestion',
            name='bmi_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbord.bmicategory'),
        ),
        migrations.AlterField(
            model_name='timebasedsuggestion',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashbord.disease'),
        ),
    ]
