# Generated by Django 5.1.2 on 2024-11-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_timebasedactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebasedsuggestion',
            name='deep_work_suggestion',
        ),
        migrations.RemoveField(
            model_name='timebasedsuggestion',
            name='nap_suggestion',
        ),
    ]
