# Generated by Django 5.1.2 on 2024-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0009_alter_timebasedsuggestion_bmi_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebasedsuggestion',
            name='disease',
            field=models.CharField(choices=[('General', 'General'), ('Diabetes', 'Diabetes'), ('Heart Disease', 'Heart Disease')], default='General', help_text='Disease associated with this suggestion', max_length=50),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
