# Generated by Django 5.1.2 on 2024-11-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0010_alter_timebasedsuggestion_disease_delete_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timebasedsuggestion',
            old_name='water_intake',
            new_name='Exercise',
        ),
    ]
