# Generated by Django 5.1.2 on 2024-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0012_alter_timebasedsuggestion_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebasedactivity',
            name='time_period',
            field=models.CharField(choices=[('Morning', '9 AM - 12 PM'), ('Afternoon', '1 PM - 3 PM'), ('Evening', '3 PM - 5 PM'), ('Night', '9 PM - 1 AM')], max_length=20, unique=True),
        ),
    ]
