# Generated by Django 5.1.2 on 2024-11-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the disease category.')),
            ],
            options={
                'verbose_name': 'Disease Category',
                'verbose_name_plural': 'Disease Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='healthcaresuggestion',
            options={'ordering': ['disease_category'], 'verbose_name': 'Healthcare Suggestion', 'verbose_name_plural': 'Healthcare Suggestions'},
        ),
        migrations.RemoveField(
            model_name='healthcaresuggestion',
            name='disease',
        ),
        migrations.AlterField(
            model_name='healthcaresuggestion',
            name='suggestion',
            field=models.TextField(help_text='Detailed health suggestion for this disease category.'),
        ),
        migrations.AddField(
            model_name='healthcaresuggestion',
            name='disease_category',
            field=models.ForeignKey(blank=True, help_text='Category of disease this suggestion relates to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='healthcare.diseasecategory'),
        ),
    ]
