# Generated by Django 5.1.2 on 2024-11-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_diseasecategory_alter_healthcaresuggestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcaresuggestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='healthcaresuggestion',
            name='updated_at',
        ),
    ]
