# Generated by Django 5.1.2 on 2024-11-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
