# Generated by Django 5.1.2 on 2024-11-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
