# Generated by Django 5.1.2 on 2024-11-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_unit',
            field=models.CharField(choices=[('m', 'Meters'), ('ft', 'Feet')], default='m', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=7),
        ),
    ]
