# Generated by Django 5.1.2 on 2024-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0008_alter_userprofile_height_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Underweight', 'Underweight'), ('Normal', 'Normal'), ('Overweight', 'Overweight'), ('Obese', 'Obese')], max_length=15, unique=True)),
                ('diet_suggestion', models.TextField()),
                ('exercise_suggestion', models.TextField()),
                ('water_intake_suggestion', models.TextField()),
                ('other_health_tips', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
