# Generated by Django 5.1.2 on 2024-11-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0013_alter_userprofile_height_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disease_history',
            field=models.CharField(choices=[('General', 'General'), ('Diabetes', 'Diabetes'), ('Heart Disease', 'Heart Disease')], default='General', help_text='Select any pre-existing condition', max_length=50),
        ),
    ]
