# Generated by Django 5.1.2 on 2024-11-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0014_userprofile_disease_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_pictures/default-profile.png', upload_to='profile_pictures/'),
        ),
    ]
