# Generated by Django 5.1.3 on 2024-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiInput', '0016_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disease_history',
            field=models.CharField(choices=[('General', 'General'), ('Heart Disease', 'Heart Disease')], default='General', help_text='Select any pre-existing condition', max_length=50),
        ),
    ]
